# Generated by Django 2.2.1 on 2019-08-31 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forth_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='uemail',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='ufirst_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='ulast_name',
        ),
    ]
